### ISSUE TITLE
A field to set a message on the login page

### ISSUE THREAD

**Issue by Magneticdud** [bpatrik/pigallery2#247]
It could be useful to have a customizable message in the login form.

Examples:

* I give a shared link to my family, they watch the shared gallery. If they go back to the domain by changing the URL, they get the login page. It would be useful to write something like "You want access to the whole gallery? Just ask Mark for your login"
* Someone wants to have the gallery "almost" public, protected by password so bots won't index it, but also humans can login. So he can write "access it with demo:demo". This could also be useful if enhancement #188 is ever implemented, so the login info that the admin writes on the login page is more restricted

**Comment by bpatrik** [comment]
If I understand your use-cases correctly, "remember me" and browser saving the user+password should solve this issue.

If you need more complex authentication, I recommend you using some reverse proxy and set that up to do the authentication.

**Comment by Magneticdud** [comment]
I thought about and maybe a dialog with login info under the login isn't a good idea, it's still not user friendly and probably not pretty

If anyone is interested, my solution (a message that tells my family to ask me the password) is something like this from the nginx proxy (that anyways need to be run anyway in my case)

```
        root /var/www/;
        index index.html;
        location / {
                try_files $uri $uri/ =404;
        }
        location /gallery/ {
                proxy_pass http://127.0.0.1:802/;
                proxy_set_header X-Forwarded-For $remote_addr;
                proxy_set_header Host $host;
                proxy_set_header  X-Real-IP  $remote_addr;
        }
```

index.html contains the intro to pigallery2 and a link to the login page, then in pigallery2 config.json set the directory to gallery (or your choice) or it will give error 404

also in this way i could place a robots.txt with disallow all

**Comment by bpatrik** [comment]
If you prepare a robots.txt with PR, I would be happy to merge it. That could be useful.

**Comment by Magneticdud** [comment]
Ok I'll include with the next part of the italian translation (or you prefer a separate PR?)

We can all agree that it's "disallow all", right? Nobody wants their private gallery indexed by search engines, I guess.

**Comment by bpatrik** [comment]
I think it's ok if you do in one PR.

Yes disallow all is good. If needed I can make it later configurable.

Thanks!

-- Sorry for being brief, sent from my phone.

Magneticdud ***@***.***> ezt írta (időpont: 2021. ápr. 4., V
16:19):

**Comment by bpatrik** [comment]
If I understand correctly, there is no more action here. Thanks for your contribution
