### ISSUE TITLE
Files with "%" can't be accessed

### ISSUE THREAD

**Issue by SlavikCA** [bpatrik/pigallery2#272]
Steps to reproduce:
- have a photo file with "%" character. For example I have "Caesarea%20bay.jpg"
- open it in the app

Result:
- thumbnail is not displayed, photo is not displayed.
- HTTP 500 error in the browser
-  server error:
```
ErrorDTO {
  code: 7,
  message: 'no such file:Христианские обои/Caesarea bay.jpg',
  details: "can't find file: /app/data/images/Христианские обои/Caesarea bay.jpg",
  request: { method: '', url: '' },
  detailsStr: "can't find file: /app/data/images/Христианские обои/Caesarea bay.jpg"
}
```

Note, that file name in the server log looks to be HTML decoded (%20 gets decoded to SPACE char). That's why "no such file".

**Environment (please complete the following information):**
 - OS: Docker

**Used app version**:
- docker latest as of Apr 25, 2021

**Comment by bpatrik** [comment]
Thanks, I'll look into it. Might be related to #205

**Comment by bpatrik** [comment]
Latest commit should fix it

**Comment by SlavikCA** [comment]
Issue still exists for `%`:

5/4/2021, 9:11:45 PM[WARN] Handled error:
ErrorDTO {
  code: 7,
  message: 'no such file:Христианские обои/Клипарт/Acts/Joгrneys of Paul/Journey to Rome/Caesarea bay.jpg',
  details: "can't find file: /app/data/images/Христианские обои/Клипарт/Acts/Joгrneys of Paul/Journey to Rome/Caesarea bay.jpg",
  request: { method: '', url: '' },
  detailsStr: "can't find file: /app/data/images/Христианские обои/Клипарт/Acts/Joгrneys of Paul/Journey to Rome/Caesarea bay.jpg"
}

Here are the files:

slavik@ds1817:/volume1/hosting/piG-test$ ls -l /volume1/pix/Posters/Христианские\ обои/Клипарт/Acts/Joгrneys\ of\ Paul/Journey\ to\ Rome/
total 168
-rwxrwxrwx+ 1 slavik users  7366 Oct  2  2003 Appian2.jpg
drwxrwxrwx+ 1 slavik users   224 Mar  4  2017 Caesarea
-rwxrwxrwx+ 1 slavik users 25557 Oct  2  2003 Caesarea%20bay.jpg

**Comment by SlavikCA** [comment]
What's interesting, is that now there is no HTTP 500.

Everything is HTTP 200:

**Request:**
/api/gallery/content/%D0%A5%D1%80%D0%B8%D1%81%D1%82%D0%B8%D0%B0%D0%BD%D1%81%D0%BA%D0%B8%D0%B5%20%D0%BE%D0%B1%D0%BE%D0%B8/%D0%9A%D0%BB%D0%B8%D0%BF%D0%B0%D1%80%D1%82/Acts/Jo%D0%B3rneys%20of%20Paul/Journey%20to%20Rome?klm=1604038381569&kls=1620162700874

**Response:**
HTTP 200
{"error":null,"result":{"directory":null,"searchResult":null,"notModified":true}}

**Request URL:**
/api/gallery/content/%D0%A5%D1%80%D0%B8%D1%81%D1%82%D0%B8%D0%B0%D0%BD%D1%81%D0%BA%D0%B8%D0%B5%20%D0%BE%D0%B1%D0%BE%D0%B8/%D0%9A%D0%BB%D0%B8%D0%BF%D0%B0%D1%80%D1%82/Acts/Jo%D0%B3rneys%20of%20Paul/Journey%20to%20Rome/Caesarea%20bay.jpg/thumbnail/240

**Response:**
HTTP/1.1 200 OK
X-Powered-By: Express
Content-Type: application/json; charset=utf-8
"This request has no response data available"

**Comment by bpatrik** [comment]
By the first look it seems to me that you tried it out too early. I takes about 40mins to build the new docker container.
Can you make sure, your version is passed  a8d6367 ?

**Comment by SlavikCA** [comment]
My apology. You're right - I didn't have latest image, because I didn't realize, that building Docker image takes that much time.

I pulled the image now and it seems to be working - I can see all photos.

However, I still see errors in the log:
5/5/2021, 6:38:26 PM[WARN] Handled error:
ErrorDTO {
  code: 7,
  message: 'no such file:Христианские обои/Клипарт/St Peter/Schlingerman%2520-%2520St%2520Peter.jpg',
  details: "can't find file: /app/data/images/Христианские обои/Клипарт/St Peter/Schlingerman%2520-%2520St%2520Peter.jpg",
  request: { method: '', url: '' },
  detailsStr: "can't find file: /app/data/images/Христианские обои/Клипарт/St Peter/Schlingerman%2520-%2520St%2520Peter.jpg"
}

$ ls -l /volume1/pix/Posters/Христианские\ обои/Клипарт/St\ Peter/
-rwxrwxrwx+ 1 slavik users 17048 Oct  2  2003 Schlingerman%20-%20St%20Peter.jpg

I'll spend more time troubleshooting the exact steps to reproduce in the next few days

**Comment by SlavikCA** [comment]
I see, that the web page sends 2 requests.
One fails:
/api/gallery/content/%D0%A5%D1%80%D0%B8%D1%81%D1%82%D0%B8%D0%B0%D0%BD%D1%81%D0%BA%D0%B8%D0%B5%20%D0%BE%D0%B1%D0%BE%D0%B8/%D0%9A%D0%BB%D0%B8%D0%BF%D0%B0%D1%80%D1%82/St%20Peter/Schlingerman%252520-%252520St%252520Peter.jpg/thumbnail/240

Another works:
/api/gallery/content/%D0%A5%D1%80%D0%B8%D1%81%D1%82%D0%B8%D0%B0%D0%BD%D1%81%D0%BA%D0%B8%D0%B5%20%D0%BE%D0%B1%D0%BE%D0%B8/%D0%9A%D0%BB%D0%B8%D0%BF%D0%B0%D1%80%D1%82/St%20Peter/Schlingerman%2520-%2520St%2520Peter.jpg/thumbnail/240

Looks like something is double-encoding

**Comment by bpatrik** [comment]
Oh I see the issue:
For directories and faces indeed its double encoding.

Every photo path encoded here:
https://github.com/bpatrik/pigallery2/blob/a8d636776ba8e601ba0a09435c3dd2ab848b9d6b/src/frontend/app/ui/gallery/MediaIcon.ts#L26-L35

Directories and faces reenocded here:
https://github.com/bpatrik/pigallery2/blob/5ad9a65a01092c11fa020d99a2ed23d23d0e1c8d/src/frontend/app/ui/gallery/directories/directory/directory.gallery.component.ts#L34-L39

https://github.com/bpatrik/pigallery2/blob/5ad9a65a01092c11fa020d99a2ed23d23d0e1c8d/src/frontend/app/ui/faces/face/face.component.ts#L46-L50

I will need to think through if the second encoding can be safely removed. Or the first should be modified.

**Comment by bpatrik** [comment]
I made some changes, I think this should be ok now.
(please not that docker tags have been changed recently : https://hub.docker.com/repository/docker/bpatrik/pigallery2/tags)

**Comment by SlavikCA** [comment]
Works perfectly: no errors and all photos are showing up correctly!

Huge thanks for this project!

**Comment by SlavikCA** [comment]
Works perfectly: no errors and all photos are showing up correctly!

Huge thanks for this project!
