### ISSUE TITLE
Search from_date / to_date use index date instead of image creation date

### ISSUE THREAD

**Issue by sadmin91** [bpatrik/pigallery2#312]
**Describe the bug**

When a search is done with `from_date` or `to_date` criteria, these criteria use index date instead of image creation date. 

**Expected behaviour**

Create a specific criteria to search from / to date based on image creation date.
Then rename existing `from_date` or `to_date` criteria to clarify that is based on index date.

**Environment (please complete the following information):**
 - OS: server on docker (hosted on raspberry pi), browser on linux Ubuntu
 - Browser: Firefox 88

**Used app version**:
- docker tag: 1.8.5-alpine

**Comment by bpatrik** [comment]
Hi

The from and to (recently renamed to `after` and `before`) uses the creation date (date the photo was taken), so it should work.

There was a new release yesterday, please check that.

**Comment by sadmin91** [comment]
Hello,
I have tryed with last nightly-alpine version.
But it's doesn't work better.

**Comment by bpatrik** [comment]
The app only maintains one type of date which should be the creation data from the exif tag. If it cannot find the creation date, it looks up the file creation, modification date. 
You can check what kind of data it could find for a photo by checking the info tab: 
![kép](https://user-images.githubusercontent.com/7512182/119721607-9bd2e580-be6b-11eb-967e-655133dcc23a.png)


Having a look, it seems that there is a date parsing issue in the search

**Comment by bpatrik** [comment]
Replaced the date format to ISO date as parsing anything else depends on the implementation.

This should resolve the issue.

(pls. wait 40 mins before trying out for the docker container to build)

**Comment by sadmin91** [comment]
Hello,

I have tryed with last nightly-alpine version (built yesterday at 10:20 PM) but the behaviour is still present:
On my galery, I search for a photo taken on 11/22/2020 with this query `after:2020-11-20 and before:2020-11-25` and no result is return.

**Comment by bpatrik** [comment]
That is strange. It works in the demo app:
Searching for the image from https://github.com/bpatrik/pigallery2/issues/312#issuecomment-849072622

https://pigallery2.herokuapp.com/search/%7B%22type%22:1,%22list%22:%5B%7B%22type%22:10,%22value%22:1433980800000%7D,%7B%22type%22:11,%22value%22:1434067200000%7D%5D%7D
![kép](https://user-images.githubusercontent.com/7512182/119882640-ec5f4700-bf2e-11eb-8c93-631b6bed8c66.png)

Can you make sure that the date of photo that you are searching for is properly recognized, by checking it at the info tab/bar of the photo?

Also what browser are you using? Can you test it in chrome/firefox?

**Comment by sadmin91** [comment]
I have uploaded an example of photo informations and search result.
![image](https://user-images.githubusercontent.com/6031110/119884558-10238c80-bf31-11eb-9509-09df7aadf67e.png)
![image](https://user-images.githubusercontent.com/6031110/119884582-17e33100-bf31-11eb-96cc-d1098c3db4ac.png)

I am using Firefox 88 on Linux Ubuntu as browser.

**Comment by sadmin91** [comment]
I have done the same query as your screenshot on demo site and I observe the same behaviour: no result for this query.
I have tested with:
- Firefox 88 on Linux Ubuntu
- Firefox 88 on Windows 10
- Edge 90 on Windows 10

**Comment by bpatrik** [comment]
I'm giving an other try to it. 
My **guess** is that in your browser Date.parse does not work as I would expect. (technically it can be a [bit random](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/parse), but I would not expect to be this random)
You can try something like this in a developer console: `Date.parse("2020-11-20")`. My guess this does not return with a valid timestamp. This issue is also visible in the url: if for the query `{type:10, value:<timepsamp>}` timestamp is not a valid timestamp (number), but rather a string, then the parsing is the issue.

e63a7ca should solve it. If this is not the issue I have no idea.

**Comment by sadmin91** [comment]
I have tested with the last nightly-alpine version and I always have this behaviour.
See below the result of `Date.parse` command on my developer console:
![image](https://user-images.githubusercontent.com/6031110/120107877-04b7a780-c163-11eb-9ac8-fe91d5c79e7c.png)

**Comment by bpatrik** [comment]
That json does not look good :/

Dates `value` should be a timestamp (number type):
https://github.com/bpatrik/pigallery2/blob/e26c60d67b265dc64dbdafc8844ca9f8fc4a3d09/src/common/entities/SearchQueryDTO.ts#L179-L188

human readable search types are: 
https://github.com/bpatrik/pigallery2/blob/e26c60d67b265dc64dbdafc8844ca9f8fc4a3d09/src/common/entities/SearchQueryDTO.ts#L3-L10

Type looks correct, but the value of the date is not.

I will need to take a deeper look. If in the meantime you see anything odd, let me know.

This is how I stringify and parse the date: 
https://github.com/bpatrik/pigallery2/blob/e26c60d67b265dc64dbdafc8844ca9f8fc4a3d09/src/common/SearchQueryParser.ts#L63-L103

**Comment by bpatrik** [comment]
Closing this due to inactivity
