### ISSUE TITLE
docker pigallery2-only cannot start. Accessing non-existent property 'padLevels' inside circular dependency

### ISSUE THREAD

**Issue by kolydart** [bpatrik/pigallery2#323]
**Describe the bug**

Starting a new, clean docker-compose/pigallery2-only v.1.8.2+ returns error `(node:1) Warning: Accessing non-existent property 'padLevels' of module exports inside circular dependency`.
Created two identical docker-compose.yml files in an empty dir. The only different parameter is the image version (bpatrik/pigallery2:1.8.0 vs bpatrik/pigallery2:latest). The first docker-compose.yml completes startup on `docker-compose up`. The second fails with the above error. So, error does not happen with 1.8.0; every version higher than 1.8.2 generates error. On error, the assets paths on the browser window are broken. The only thing showing on the screen is "Loading..." with a broken img icon.

**Directory structure**
```
tree
.
├── config
├── db-data
├── docker-compose.yml
└── tmp
```

**working docker-compose.yml**
```
version: '3'
services:
  pigallery2:
    image: bpatrik/pigallery2:1.8.0
    container_name: testgallery
    environment:
      - NODE_ENV=debug
    volumes:
      - "./config:/app/data/config" # CHANGE ME
      - "./db-data:/app/data/db"
      - "/mnt/external/storage/pictures/scans:/app/data/images" # CHANGE ME
      - "./tmp:/app/data/tmp" # CHANGE ME
    ports:
      - 18280:80
    restart: always

volumes:
  db-data:
```

**docker-compose.yml generating error**
```
version: '3'
services:
  pigallery2:
    image: bpatrik/pigallery2:latest
    container_name: testgallery
    environment:
      - NODE_ENV=debug
    volumes:
      - "./config:/app/data/config" # CHANGE ME
      - "./db-data:/app/data/db"
      - "/mnt/external/storage/pictures/scans:/app/data/images" # CHANGE ME
      - "./tmp:/app/data/tmp" # CHANGE ME
    ports:
      - 18280:80
    restart: always

volumes:
  db-data:
```

**screen shot**
[Brower window displays "Loading..."](https://public.kolydart.gr/Screenshot%202021-06-13%20at%201.57.20%20PM.png)

**Server logs**
* Set env variable `NODE_ENV=debug` to log everything.
```
13:39 # docker-compose up
Creating network "testgallery_default" with the default driver
Creating testgallery ... done
Attaching to testgallery
testgallery   | [Typeconfig] Loading config. Path: /app/data/config/config.json
testgallery   | [Typeconfig] cannot read defaults from file
testgallery   | Error: ENOENT: no such file or directory, open '/app/data/config/config.json'
testgallery   |     at Object.openSync (fs.js:476:3)
testgallery   |     at Object.readFileSync (fs.js:377:35)
testgallery   |     at ConfigClassType.__loadDefaultsSync (/app/node_modules/typeconfig/src/decorators/class/ConfigClass.js:107:54)
testgallery   |     at ConfigClassType.loadSync (/app/node_modules/typeconfig/src/decorators/class/ConfigClass.js:139:22)
testgallery   |     at Object.<anonymous> (/app/src/common/config/private/Config.js:86:16)
testgallery   |     at Module._compile (internal/modules/cjs/loader.js:1063:30)
testgallery   |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
testgallery   |     at Module.load (internal/modules/cjs/loader.js:928:32)
testgallery   |     at Function.Module._load (internal/modules/cjs/loader.js:769:14)
testgallery   |     at Module.require (internal/modules/cjs/loader.js:952:19) {
testgallery   |   errno: -2,
testgallery   |   syscall: 'open',
testgallery   |   code: 'ENOENT',
testgallery   |   path: '/app/data/config/config.json'
testgallery   | }
testgallery   | [Typeconfig] Loading defaults, def prefix: default
testgallery   | [Typeconfig] no default cli found among these: {
testgallery   | 	"expose": {
testgallery   | 		"gc": true
testgallery   | 	},
testgallery   | 	"config": {
testgallery   | 		"path": "/app/data/config/config.json"
testgallery   | 	}
testgallery   | }
testgallery   | [Typeconfig] from env: {
testgallery   | 	"Server": {
testgallery   | 		"Database": {
testgallery   | 			"dbFolder": "/app/data/db"
testgallery   | 		},
testgallery   | 		"Media": {
testgallery   | 			"folder": "/app/data/images",
testgallery   | 			"tempFolder": "/app/data/tmp"
testgallery   | 		}
testgallery   | 	}
testgallery   | }
testgallery   | [Typeconfig] cannot read config from file
testgallery   | Error: ENOENT: no such file or directory, open '/app/data/config/config.json'
testgallery   |     at Object.openSync (fs.js:476:3)
testgallery   |     at Object.readFileSync (fs.js:377:35)
testgallery   |     at ConfigClassType.loadSync (/app/node_modules/typeconfig/src/decorators/class/ConfigClass.js:142:54)
testgallery   |     at Object.<anonymous> (/app/src/common/config/private/Config.js:86:16)
testgallery   |     at Module._compile (internal/modules/cjs/loader.js:1063:30)
testgallery   |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
testgallery   |     at Module.load (internal/modules/cjs/loader.js:928:32)
testgallery   |     at Function.Module._load (internal/modules/cjs/loader.js:769:14)
testgallery   |     at Module.require (internal/modules/cjs/loader.js:952:19)
testgallery   |     at require (internal/modules/cjs/helpers.js:88:18) {
testgallery   |   errno: -2,
testgallery   |   syscall: 'open',
testgallery   |   code: 'ENOENT',
testgallery   |   path: '/app/data/config/config.json'
testgallery   | }
testgallery   | [Typeconfig] config file does not exists yet. This can be normal
testgallery   | Error: ENOENT: no such file or directory, access '/app/data/config/config.json'
testgallery   |     at Object.accessSync (fs.js:220:3)
testgallery   |     at ConfigClassType.loadSync (/app/node_modules/typeconfig/src/decorators/class/ConfigClass.js:166:24)
testgallery   |     at Object.<anonymous> (/app/src/common/config/private/Config.js:86:16)
testgallery   |     at Module._compile (internal/modules/cjs/loader.js:1063:30)
testgallery   |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
testgallery   |     at Module.load (internal/modules/cjs/loader.js:928:32)
testgallery   |     at Function.Module._load (internal/modules/cjs/loader.js:769:14)
testgallery   |     at Module.require (internal/modules/cjs/loader.js:952:19)
testgallery   |     at require (internal/modules/cjs/helpers.js:88:18)
testgallery   |     at Object.<anonymous> (/app/src/backend/server.js:11:18) {
testgallery   |   errno: -2,
testgallery   |   syscall: 'access',
testgallery   |   code: 'ENOENT',
testgallery   |   path: '/app/data/config/config.json'
testgallery   | }
testgallery   | [Typeconfig] Processing cli and ENV inputs: {
testgallery   | 	"expose": {
testgallery   | 		"gc": true
testgallery   | 	},
testgallery   | 	"config": {
testgallery   | 		"path": "/app/data/config/config.json"
testgallery   | 	}
testgallery   | }
testgallery   | [Typeconfig] Processing cli and ENV inputs: {
testgallery   | 	"PATH": "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
testgallery   | 	"HOSTNAME": "9cdbcd2c7733",
testgallery   | 	"NODE_ENV": "debug",
testgallery   | 	"NODE_VERSION": "14.16.1",
testgallery   | 	"YARN_VERSION": "1.22.5",
testgallery   | 	"PI_DOCKER": true,
testgallery   | 	"HOME": "/root"
testgallery   | }
testgallery   | NODE_ENV environmental variable is set to debug, forcing all logs to print
testgallery   | 6/13/2021, 10:41:25 AM[INFO] [server] Running in DEBUG mode, set env variable NODE_ENV=production to disable
testgallery   | 6/13/2021, 10:41:25 AM[INFO] [server] running diagnostics...
testgallery   | (node:1) Warning: Accessing non-existent property 'padLevels' of module exports inside circular dependency
testgallery   | (Use `node --trace-warnings ...` to show where the warning was created)
testgallery   | 6/13/2021, 10:41:25 AM[INFO] Updating database scheme
testgallery   | 6/13/2021, 10:41:32 AM[VERBOSE] [server] using config from /app/data/config/config.json:
testgallery   | 6/13/2021, 10:41:32 AM[VERBOSE] [server] {
testgallery   | 	"Server": {
testgallery   | 		"sessionSecret": [
testgallery   | 			"4d18b3661ac8b9532771eebaf726e9fbd3e6105534987a61ded4311dd359c02a56e522a408e79111e1f6f0a249ba43f0fc78a34f3dd266b98b8f04a1894975c5899083045b90ecefbd5c55e531b0d121fae04c90b5564cde7740107ad65f1c043ac417ce416a1c45305401ea03f7197bb15e132f4b1b3305b7e6d1fcbd617c4f4c440ffdcaa40d228e9affb1dd40ebe8060e3988955db5dc7ba23846a82d5b3f41c0dadc0d414a917aabc1d4eb1c7b661a7102409c466b15585e15c9d287f5a0d0312b8fc277fe82a0cdfee3200423191be77c2bcf87b0a2c05da9a4ea1f7bac1f73b58a986377c7a4e274e4d5a3e7a070849332c302211e8b1d4ea12fd7e51a",
testgallery   | 			"f3cbc6d568a43af72986689ffb9d652142b5fc8fe47292d5f0f6fa1b03bc86fbb41c092e0885b182a5579350ae7b5239e9cbd9f7e026d75e68f90a272812d71692679953a46e64bd7c2976e3de0c9af0051a10f6fe100f761b0072a442f618f91607ff7b5a11c7c94aa8dd2cda4b7a1e56acc7bed69923c4af131354fd8b4dcea5983fbc310a3fb44969ec8a8425412150e395f342d172376806028147304ef78460e9d48cbb8d6a20d9bfb216f520f616b432c6100f6832596f1be4dfc99bd212a6895f79f7746a69b043dfacc18ff9efe323e7adb04448584ce79fcf8f5935d9f16cdceb346e3a6c6d24e1bd8c324f1a00f1e47dae53b729d01536fb35bda9",
testgallery   | 			"d07794e07e658a72fa893b558608613a3567862947157476d9b8556a2e40cc188a70c609ed127826f1d1539d9d418c4b2bace76929d865ef0e7f3b58446ea4cb821842c208d53902def20b097ef25aef91bd6d6683613f19b237309f3f013eb5e5a6268f4e6ab5db14d814dbfa40c644c1d5c03a0bc4a05cb3399aaa5ed59ea893f802e37c0bc4abbd36a9acfec0890f63e7255af653406bf16d0d4e541e2b86e6101144caf0bfd914518ef57e6d1a11fafb2619fe338d7dfb22530d8788c2a4a636ea8c89e5da5a96b46be76ebf3df5a72299774296ddbe8356fe194509cb5a8ad17431b175e7ce965c43fcf7c5e33112dda489058ab545f86545d060ddad9a"
testgallery   | 		],
testgallery   | 		"port": 80,
testgallery   | 		"host": "0.0.0.0",
testgallery   | 		"Media": {
testgallery   | 			"//[folder]": "Images are loaded from this folder (read permission required)",
testgallery   | 			"folder": "/app/data/images",
testgallery   | 			"//[tempFolder]": "Thumbnails, coverted photos, videos will be stored here (write permission required)",
testgallery   | 			"tempFolder": "/app/data/tmp",
testgallery   | 			"Video": {
testgallery   | 				"transcoding": {
testgallery   | 					"bitRate": 5242880,
testgallery   | 					"resolution": 720,
testgallery   | 					"fps": 25,
testgallery   | 					"codec": "libx264",
testgallery   | 					"format": "mp4",
testgallery   | 					"//[crf]": "Constant Rate Factor. The range of the CRF scale is 0–51, where 0 is lossless, 23 is the default, and 51 is worst quality possible.",
testgallery   | 					"crf": 23,
testgallery   | 					"//[preset]": "A preset is a collection of options that will provide a certain encoding speed to compression ratio",
testgallery   | 					"preset": "medium",
testgallery   | 					"//[customOptions]": "It will be sent to ffmpeg as it is, as custom options.",
testgallery   | 					"customOptions": []
testgallery   | 				}
testgallery   | 			},
testgallery   | 			"Photo": {
testgallery   | 				"Converting": {
testgallery   | 					"//[onTheFly]": "Converts photos on the fly, when they are requested.",
testgallery   | 					"onTheFly": true,
testgallery   | 					"resolution": 1080
testgallery   | 				}
testgallery   | 			},
testgallery   | 			"Thumbnail": {
testgallery   | 				"//[qualityPriority]": "if true, photos will have better quality.",
testgallery   | 				"qualityPriority": true,
testgallery   | 				"personFaceMargin": 0.6
testgallery   | 			}
testgallery   | 		},
testgallery   | 		"Threading": {
testgallery   | 			"//[enabled]": "App can run on multiple thread",
testgallery   | 			"enabled": true,
testgallery   | 			"//[thumbnailThreads]": "Number of threads that are used to generate thumbnails. If 0, number of 'CPU cores -1' threads will be used.",
testgallery   | 			"thumbnailThreads": 0
testgallery   | 		},
testgallery   | 		"Database": {
testgallery   | 			"type": "sqlite",
testgallery   | 			"dbFolder": "/app/data/db",
testgallery   | 			"sqlite": {
testgallery   | 				"DBFileName": "sqlite.db"
testgallery   | 			},
testgallery   | 			"mysql": {
testgallery   | 				"host": "localhost",
testgallery   | 				"port": 3306,
testgallery   | 				"database": "pigallery2",
testgallery   | 				"username": "",
testgallery   | 				"password": ""
testgallery   | 			}
testgallery   | 		},
testgallery   | 		"Sharing": {
testgallery   | 			"updateTimeout": 300000
testgallery   | 		},
testgallery   | 		"//[sessionTimeout]": "unit: ms",
testgallery   | 		"sessionTimeout": 604800000,
testgallery   | 		"Indexing": {
testgallery   | 			"cachedFolderTimeout": 3600000,
testgallery   | 			"reIndexingSensitivity": "low",
testgallery   | 			"//[excludeFolderList]": "If an entry starts with '/' it is treated as an absolute path. If it doesn't start with '/' but contains a '/', the path is relative to the image directory. If it doesn't contain a '/', any folder with this name will be excluded.",
testgallery   | 			"excludeFolderList": [
testgallery   | 				".Trash-1000",
testgallery   | 				".dtrash",
testgallery   | 				"$RECYCLE.BIN"
testgallery   | 			],
testgallery   | 			"//[excludeFileList]": "Any folder that contains a file with this name will be excluded from indexing.",
testgallery   | 			"excludeFileList": []
testgallery   | 		},
testgallery   | 		"//[photoMetadataSize]": "only this many bites will be loaded when scanning photo for metadata",
testgallery   | 		"photoMetadataSize": 524288,
testgallery   | 		"Duplicates": {
testgallery   | 			"listingLimit": 1000
testgallery   | 		},
testgallery   | 		"Log": {
testgallery   | 			"level": "info",
testgallery   | 			"sqlLevel": "error"
testgallery   | 		},
testgallery   | 		"Jobs": {
testgallery   | 			"//[maxSavedProgress]": "Job history size",
testgallery   | 			"maxSavedProgress": 10,
testgallery   | 			"scheduled": [
testgallery   | 				{
testgallery   | 					"name": "Indexing",
testgallery   | 					"jobName": "Indexing",
testgallery   | 					"config": {},
testgallery   | 					"allowParallelRun": false,
testgallery   | 					"trigger": {
testgallery   | 						"type": "never"
testgallery   | 					}
testgallery   | 				},
testgallery   | 				{
testgallery   | 					"name": "Thumbnail Generation",
testgallery   | 					"jobName": "Thumbnail Generation",
testgallery   | 					"config": {
testgallery   | 						"sizes": [
testgallery   | 							240
testgallery   | 						],
testgallery   | 						"indexedOnly": true
testgallery   | 					},
testgallery   | 					"allowParallelRun": false,
testgallery   | 					"trigger": {
testgallery   | 						"type": "after",
testgallery   | 						"afterScheduleName": "Indexing"
testgallery   | 					}
testgallery   | 				},
testgallery   | 				{
testgallery   | 					"name": "Photo Converting",
testgallery   | 					"jobName": "Photo Converting",
testgallery   | 					"config": {
testgallery   | 						"indexedOnly": true
testgallery   | 					},
testgallery   | 					"allowParallelRun": false,
testgallery   | 					"trigger": {
testgallery   | 						"type": "after",
testgallery   | 						"afterScheduleName": "Thumbnail Generation"
testgallery   | 					}
testgallery   | 				},
testgallery   | 				{
testgallery   | 					"name": "Video Converting",
testgallery   | 					"jobName": "Video Converting",
testgallery   | 					"config": {
testgallery   | 						"indexedOnly": true
testgallery   | 					},
testgallery   | 					"allowParallelRun": false,
testgallery   | 					"trigger": {
testgallery   | 						"type": "after",
testgallery   | 						"afterScheduleName": "Photo Converting"
testgallery   | 					}
testgallery   | 				},
testgallery   | 				{
testgallery   | 					"name": "Temp Folder Cleaning",
testgallery   | 					"jobName": "Temp Folder Cleaning",
testgallery   | 					"config": {
testgallery   | 						"indexedOnly": true
testgallery   | 					},
testgallery   | 					"allowParallelRun": false,
testgallery   | 					"trigger": {
testgallery   | 						"type": "after",
testgallery   | 						"afterScheduleName": "Video Converting"
testgallery   | 					}
testgallery   | 				}
testgallery   | 			]
testgallery   | 		}
testgallery   | 	},
testgallery   | 	"Client": {
testgallery   | 		"applicationTitle": "PiGallery 2",
testgallery   | 		"publicUrl": "",
testgallery   | 		"urlBase": "",
testgallery   | 		"Search": {
testgallery   | 			"enabled": true,
testgallery   | 			"searchCacheTimeout": 3600000,
testgallery   | 			"AutoComplete": {
testgallery   | 				"enabled": true,
testgallery   | 				"maxItemsPerCategory": 5,
testgallery   | 				"cacheTimeout": 3600000
testgallery   | 			},
testgallery   | 			"maxMediaResult": 2000,
testgallery   | 			"maxDirectoryResult": 200
testgallery   | 		},
testgallery   | 		"Sharing": {
testgallery   | 			"enabled": true,
testgallery   | 			"passwordProtected": true
testgallery   | 		},
testgallery   | 		"Map": {
testgallery   | 			"enabled": true,
testgallery   | 			"//[maxPreviewMarkers]": "Maximum number of markers to be shown on the map preview on the gallery page.",
testgallery   | 			"maxPreviewMarkers": 50,
testgallery   | 			"useImageMarkers": true,
testgallery   | 			"mapProvider": "OpenStreetMap",
testgallery   | 			"mapboxAccessToken": "",
testgallery   | 			"customLayers": [
testgallery   | 				{
testgallery   | 					"name": "street",
testgallery   | 					"url": ""
testgallery   | 				}
testgallery   | 			]
testgallery   | 		},
testgallery   | 		"RandomPhoto": {
testgallery   | 			"enabled": true
testgallery   | 		},
testgallery   | 		"Other": {
testgallery   | 			"enableCache": true,
testgallery   | 			"enableOnScrollRendering": true,
testgallery   | 			"defaultPhotoSortingMethod": "ascDate",
testgallery   | 			"//[enableDirectorySortingByDate]": "If enabled directories will be sorted by date, like photos, otherwise by name. Directory date is the last modification time of that directory not the creation date of the oldest photo",
testgallery   | 			"enableDirectorySortingByDate": false,
testgallery   | 			"enableOnScrollThumbnailPrioritising": true,
testgallery   | 			"NavBar": {
testgallery   | 				"showItemCount": true
testgallery   | 			},
testgallery   | 			"captionFirstNaming": false
testgallery   | 		},
testgallery   | 		"authenticationRequired": true,
testgallery   | 		"unAuthenticatedUserRole": "Admin",
testgallery   | 		"Media": {
testgallery   | 			"Thumbnail": {
testgallery   | 				"iconSize": 45,
testgallery   | 				"personThumbnailSize": 200,
testgallery   | 				"thumbnailSizes": [
testgallery   | 					240,
testgallery   | 					480
testgallery   | 				]
testgallery   | 			},
testgallery   | 			"Video": {
testgallery   | 				"enabled": true
testgallery   | 			},
testgallery   | 			"Photo": {
testgallery   | 				"Converting": {
testgallery   | 					"enabled": true
testgallery   | 				}
testgallery   | 			}
testgallery   | 		},
testgallery   | 		"MetaFile": {
testgallery   | 			"enabled": true
testgallery   | 		},
testgallery   | 		"Faces": {
testgallery   | 			"enabled": true,
testgallery   | 			"keywordsToPersons": true,
testgallery   | 			"writeAccessMinRole": "Admin",
testgallery   | 			"readAccessMinRole": "User"
testgallery   | 		}
testgallery   | 	}
testgallery   | }
testgallery   | 6/13/2021, 10:41:32 AM[SILLY] Creating thread pool with 1 workers
testgallery   | 6/13/2021, 10:41:33 AM[DEBUG] Worker 19 is online, worker count: 1
testgallery   | [Typeconfig] Loading config. Path: /app/data/config/config.json
testgallery   | [Typeconfig] Loading defaults from file: undefined
testgallery   | [Typeconfig] Loading defaults, def prefix: default
testgallery   | [Typeconfig] no default cli found among these: {
testgallery   | 	"expose": {
testgallery   | 		"gc": true
testgallery   | 	},
testgallery   | 	"config": {
testgallery   | 		"path": "/app/data/config/config.json"
testgallery   | 	}
testgallery   | }
testgallery   | [Typeconfig] from env: {
testgallery   | 	"Server": {
testgallery   | 		"Database": {
testgallery   | 			"dbFolder": "/app/data/db"
testgallery   | 		},
testgallery   | 		"Media": {
testgallery   | 			"folder": "/app/data/images",
testgallery   | 			"tempFolder": "/app/data/tmp"
testgallery   | 		}
testgallery   | 	}
testgallery   | }
testgallery   | [Typeconfig] Processing cli and ENV inputs: {
testgallery   | 	"expose": {
testgallery   | 		"gc": true
testgallery   | 	},
testgallery   | 	"config": {
testgallery   | 		"path": "/app/data/config/config.json"
testgallery   | 	}
testgallery   | }
testgallery   | [Typeconfig] Processing cli and ENV inputs: {
testgallery   | 	"PATH": "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
testgallery   | 	"HOSTNAME": "9cdbcd2c7733",
testgallery   | 	"NODE_ENV": "debug",
testgallery   | 	"NODE_VERSION": "14.16.1",
testgallery   | 	"YARN_VERSION": "1.22.5",
testgallery   | 	"PI_DOCKER": true,
testgallery   | 	"HOME": "/root",
testgallery   | 	"VIPSHOME": "/target"
testgallery   | }
testgallery   | 6/13/2021, 10:41:33 AM[INFO] [JobManager] Running job schedules
testgallery   | 6/13/2021, 10:41:33 AM[DEBUG] [JobManager] skipping schedule:Indexing
testgallery   | 6/13/2021, 10:41:33 AM[DEBUG] [JobManager] skipping schedule:Thumbnail Generation
testgallery   | 6/13/2021, 10:41:33 AM[DEBUG] [JobManager] skipping schedule:Photo Converting
testgallery   | 6/13/2021, 10:41:33 AM[DEBUG] [JobManager] skipping schedule:Video Converting
testgallery   | 6/13/2021, 10:41:33 AM[DEBUG] [JobManager] skipping schedule:Temp Folder Cleaning
testgallery   | 6/13/2021, 10:41:33 AM[DEBUG] SQL DB inited
testgallery   | 6/13/2021, 10:41:33 AM[INFO] [server] Listening on port 80
testgallery   | NODE_ENV environmental variable is set to debug, forcing all logs to print
testgallery   | 6/13/2021, 10:41:33 AM[DEBUG] Worker is waiting for tasks
testgallery   | (node:19) Warning: Accessing non-existent property 'padLevels' of module exports inside circular dependency
testgallery   | (Use `node --trace-warnings ...` to show where the warning was created)
```

**Environment:**
 - OS: Raspberry Pi 4, Ubuntu 20.04.2 LTS server
 - Browser: no need for. Error is visible in CLI.

**Used app version**:
- docker-compose/pigallery2-only 1.8.0, 1.8.2+

**Comment by bpatrik** [comment]
this is not an erorr, just a warning, does not do any harm:`(node:1) Warning: Accessing non-existent property 'padLevels' of module exports inside circular dependency`
Also it is fixed in the latest version.

The error is this:

```
testgallery   | Error: ENOENT: no such file or directory, open '/app/data/config/config.json'
testgallery   |     at Object.openSync (fs.js:476:3)
testgallery   |     at Object.readFileSync (fs.js:377:35)
testgallery   |     at ConfigClassType.__loadDefaultsSync (/app/node_modules/typeconfig/src/decorators/class/ConfigClass.js:107:54)
testgallery   |     at ConfigClassType.loadSync (/app/node_modules/typeconfig/src/decorators/class/ConfigClass.js:139:22)
testgallery   |     at Object.<anonymous> (/app/src/common/config/private/Config.js:86:16)
testgallery   |     at Module._compile (internal/modules/cjs/loader.js:1063:30)
testgallery   |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
testgallery   |     at Module.load (internal/modules/cjs/loader.js:928:32)
testgallery   |     at Function.Module._load (internal/modules/cjs/loader.js:769:14)
testgallery   |     at Module.require (internal/modules/cjs/loader.js:952:19) {
testgallery   |   errno: -2,
testgallery   |   syscall: 'open',
testgallery   |   code: 'ENOENT',
testgallery   |   path: '/app/data/config/config.json'
testgallery   | }
```

There was some issue with the release pipe and the latest tag did not get updated. I deleted that to reduce confusion, try this instead `latest-debian-buster`

**Comment by kolydart** [comment]
Thank you very much for your attention!
Changing the tag, indeed removed the error.
But the browser still showed a broken [assets/icon.png](https://public.kolydart.gr/Screenshot%202021-06-13%20at%201.57.20%20PM.png).

After much trial and error, I think I nailed the bug. **It has to do with the parameter "urlBase" in config**.

In version 1.8.2 and afterwards, **the urlBase parameter is not reflected in the `<base>` href in html**.
With exactly the same `config/config.json` containing `"urlBase": "/family",` I see:
* `<base href="/family/"/>` in the html head on version `1.8.0`
* `<base href="/"/>` in the html head on version `1.8.2`+, `latest`, `latest-debian-buster`

The result of the above is that the brower gets 404 errors for each asset, [thus showing "Loading..."](https://public.kolydart.gr/Screenshot%202021-06-13%20at%201.57.20%20PM.png) which I thought it was due to the circular dependency warning.

**Comment by bpatrik** [comment]
that looks odd. might be related to the angular upgrade and the way the app is build now.

**Comment by bpatrik** [comment]
I took a quick look. I believe you have some issue with your docker setup.

changing `utlBase` works for me. I think the app cannot read your config.json (and uses the default urlbase="").
Your command line dump also suggests the same: `Error: ENOENT: no such file or directory, open '/app/data/config/config.json'`

**Comment by bpatrik** [comment]
+1
I see you set the logging to silly. That case the app dumps the used config, and you can see the `urlbase` is empy because it could not read it from the config file.

**Comment by kolydart** [comment]
> I took a quick look. I believe you have some issue with your docker setup.
> 
> changing `utlBase` works for me. I think the app cannot read your config.json (and uses the default urlbase="").
> Your command line dump also suggests the same: `Error: ENOENT: no such file or directory, open '/app/data/config/config.json'`

Indeed; your assumption was correct. I reset the config.json file and the app booted normally.
Please mark issue as solved.
THANK YOU

**Comment by bpatrik** [comment]
Happy to help!
