### ISSUE TITLE
Photos Exceed Buffer Limit

### ISSUE THREAD

**Issue by auntphil** [bpatrik/pigallery2#398]
**Describe the bug**

Large photos fail to scan the XML and do not get indexed. Happens with on demand indexing and scheduled. Is there a way to expand the buffer?

**Server logs (optional)**

In case of a server side error, provide logs:

@#[line:3,col:5]
12/4/2021, 4:24:13 PM[DEBUG][MetadataLoader] Error parsing exif /app/data/images/2021/2021-08-28 13.28.40.jpg TypeError: Corrupt JPG, exceeded buffer limits
    at validateBuffer (/app/node_modules/image-size/dist/types/jpg.js:77:15)
    at Object.calculate (/app/node_modules/image-size/dist/types/jpg.js:101:13)
    at lookup (/app/node_modules/image-size/dist/index.js:43:53)
    at Function.imageSize (/app/node_modules/image-size/dist/index.js:118:16)
    at /app/src/backend/model/threading/MetadataLoader.js:160:55
    at FSReqCallback.wrapper [as oncomplete] (fs.js:562:5)
[xmldom warning]	unclosed xml attribute 

**Environment (please complete the following information):**
 - OS: Windows
 - Browser All

**Used app version**:
- docker-nightly
- ect..

**Comment by auntphil** [comment]
Needed to increase the buffer size. Read the manual and increased the Server-photoMetadataSize value. Fixed the issue. RTFM

**Comment by AxiomOfChoices** [comment]
Hello, what did you end up setting it to? I am having the same problem and can't seem to fix it.

**Comment by bpatrik** [comment]
To the smallest value that does not break the gallery. (Higher the value the sliver is the indexing, otherwise does not hurt).

You can try doubling the number.

This issue should be gone once https://github.com/bpatrik/pigallery2/issues/277 is fixed.

**Comment by AxiomOfChoices** [comment]
That's good to know! Can't wait for that update. In the meanwhile should I set it to above the size of the my largest files? Because I tried doubling it and it didn't fix the problem unfortunately and testing it is very difficult since the indexing of the folder with the problematic file takes quite some time already.
